### ISSUE TITLE
Bad arguments to ParseException in Log.error

### ISSUE THREAD

**Issue by leo-fmr** [klahnakoski/mo-parsing#23]
While parsing complex SQL with mo_sql_parsing I got this error (most of the stack removed):
```
  . . .
  File "my-project/venv/lib/python3.8/site-packages/mo_parsing/utils.py", line 49, in error
    raise ParseException(Null, -1, -1, "", msg=template, cause=cause)
TypeError: __init__() got multiple values for argument 'msg'
```
This is caused by an extra positional argument to ParseException causing an extra value for msg.

**Comment by klahnakoski** [comment]
https://github.com/klahnakoski/mo-parsing/commit/71ccac294346f5cbecdf3a972433688cb3f0fbb3

**Comment by klahnakoski** [comment]
https://pypi.org/project/mo-parsing/8.192.22229/

**Comment by klahnakoski** [comment]
@leo-fmr  Thank you very much for catching this.  Even though it is fixed (and there is an installation test for this).  I should attempt to add this class to the code coverage: https://coveralls.io/builds/51728378/source?filename=mo_parsing%2Futils.py#L34
